site:
  title: Devronomicon
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://videohexsoftware.github.io/devronomicon
  start_page: tools::index.adoc
content:
  sources:
  - url: https://github.com/VideoHexSoftware/devronomicon-tools.git
    branches: main
    # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
    # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
    edit_url: false
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
    # fix for GitHub Pages
    # https://docs.antora.org/antora/latest/publish-to-github-pages/
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll